config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  root "welcome#index"
  resource :retirements

  resources :events do
    resources :tickets
  end

  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :tickets, dependent: :destroy

  validates :name, length: {maximum: 50}, presence: true
  validates :place, length: {maximum: 100}, presence: true
  validates :content, length: {maximum: 200}, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "は終了時間よりも前に設定してください")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.where("start_at")
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: "作成しました"
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_at, :end_at
    )
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("layouts/errors", errors: @event.errors) %>"

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<h1>イベント情報編集</h1>

<%= form_with(model: @event, class: "") do |f| %>
  <div id="errors"></div>
  <%= f.label :name %>
  <%= f.text_field :name, class: "" %><br/>
  <%= f.label :place %>
  <%= f.text_field :place, class: "" %><br/>
  <%= f.label :start_at %>
  <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1 %><br/>
  <%= f.label :end_at %>
  <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1 %><br/>
  <%= f.label :content %>
  <%= f.text_area :content, class: "" %><br/>
  <%= f.submit class: "" %>
<% end %>

app/views/events/index.html.erb
<h1>イベント一覧</h1>

<ul>
  <% @events.each do |event| %>
    <%= link_to(event, class: "") do %>
      <h5><%= event.name %></h5>
      <p><%= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}" %></p>
    <% end %>
  <% end %>
</ul>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<%= form_with(model: @event, class: "") do |f| %>
  <div id="errors"></div>
  <%= f.label :name %>
  <%= f.text_field :name, class: "" %><br/>
  <%= f.label :place %>
  <%= f.text_field :place, class: "" %><br/>
  <%= f.label :start_at %>
  <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1 %><br/>
  <%= f.label :end_at %>
  <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1 %><br/>
  <%= f.label :content %>
  <%= f.text_area :content, class: "" %><br/>
  <%= f.submit class: "" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h5>イベント内容</h5>
<p><%= @event.content %></p>
<h5>開催時間</h5>
<p><%= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}" %></p>
<h5>開催場所</h5>
<p><%= @event.place %></p>
<h5>主催者</h5>
<% if @event.owner %>
  <p><%= @event.owner.name %></p>
<% else%>
  退会したユーザーです。
<% end %>

<% if @event.created_by?(current_user) %>
  <%= link_to "イベントを編集する", edit_event_path(@event), class: "" %>
  <%= link_to "イベントを削除する", event_path(@event), class: "", method: :delete, data: {confirm: "本当に削除しますか？" } %>
<% end %>

<% if @ticket %>
  <%= link_to "参加をキャンセルする", event_ticket_path(@event, @ticket), method: :delete, class: "" %>
<% elsif user_signed_in? %>
  <%= form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f| %>
    <div id="createTicketsErrors"></div>
    <%= f.text_field :comment %>
    <%= f.submit "参加する", class: "" %>
  <% end %>
<% end %>

<h5>参加者</h5>
<ul>
  <% @tickets.each do |ticket| %>
    <li>
      <% if ticket.user %>
        <%= "#{ticket.user.name}" %>
      <% else %>
        退会したユーザーです。
      <% end %>
    </li>
  <% end %>
</ul>

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("layouts/errors", errors: @event.errors) %>"